### ISSUE TITLE
Typo in functions chapter in Default Argument section

### ISSUE THREAD

**Issue by surajssd** [kushaldas/pym#90]
Two typos in [function chapter default argument section](http://pymbook.readthedocs.org/en/latest/functions.html#default-argument-value):

> In a function variables may have default argument values, that means if we don’t give any value for that particular variable it will assigned automatically.

there should be *be* after *it will*
and in the second paragraph:

> In the above example we have written b = -99 in the function parameter list. That means of no value for b is given then b’s value is -99.

typing mistake there is *of* instead of *if*

**Comment by kushaldas** [comment]
Merged, thanks  :)
